services:
  awg:
    build:
      context: ./docker/awg
    depends_on:
      api:
        condition: service_started
        restart: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - AWG_SUBNET_IP
      - WIREGUARD_SUBNET_CIDR
    volumes:
      - /lib/modules:/lib/modules:ro
      - awg_data:/etc/wireguard:ro
    ports:
      - ${AWG_SERVER_PORT}:${AWG_SERVER_PORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun
    restart: always

  api:
    build:
      context: .
    # healthcheck:
      # test: ["CMD", "cat", "/configs/awg/wg0.conf"]
      # interval: 5s
    volumes:
      - awg_data:/configs/awg
    env_file: .env

volumes:
  awg_data:

